// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcBKCxWhxaF_RAuKtkWjRArGJKIx38zE',
    appId: '1:516243239487:web:21d08499cc5aaedaeb3e8a',
    messagingSenderId: '516243239487',
    projectId: 'green-app-29517',
    authDomain: 'green-app-29517.firebaseapp.com',
    storageBucket: 'green-app-29517.firebasestorage.app',
    measurementId: 'G-46J6JCQRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Qy7SFLCTeMY5B1lSrD1Mu91tAqdzIM4',
    appId: '1:516243239487:android:5f6fca96a9927702eb3e8a',
    messagingSenderId: '516243239487',
    projectId: 'green-app-29517',
    storageBucket: 'green-app-29517.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMq5jPZV8Nilar5VEfFod_0l5rgNrlKmI',
    appId: '1:516243239487:ios:2ab1031051c8197beb3e8a',
    messagingSenderId: '516243239487',
    projectId: 'green-app-29517',
    storageBucket: 'green-app-29517.firebasestorage.app',
    iosBundleId: 'com.example.greenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMq5jPZV8Nilar5VEfFod_0l5rgNrlKmI',
    appId: '1:516243239487:ios:2ab1031051c8197beb3e8a',
    messagingSenderId: '516243239487',
    projectId: 'green-app-29517',
    storageBucket: 'green-app-29517.firebasestorage.app',
    iosBundleId: 'com.example.greenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxcBKCxWhxaF_RAuKtkWjRArGJKIx38zE',
    appId: '1:516243239487:web:c78f61c518d910dbeb3e8a',
    messagingSenderId: '516243239487',
    projectId: 'green-app-29517',
    authDomain: 'green-app-29517.firebaseapp.com',
    storageBucket: 'green-app-29517.firebasestorage.app',
    measurementId: 'G-J1Z7VE7W2D',
  );
}
